spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestao_academica?useSSL=false&serverTimezone=UTC
    username: app_user
    password: AppUser#2025!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  secret: super-secret-chave-mesmo-teste
  expiration: 3600000

server:
  port: 8080
